version: "3.5"

services:
  diun:
    image: crazymax/diun:latest
    hostname: {{ grains.id.split('.')[0] }}-diun
    volumes:
      - "./data:/data"
      - "./diun.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Berlin"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    restart: always
